name: next_feature
description: A CLI tool to generate Flutter feature folder structure with clean architecture.
version: 0.1.0
repository: https://github.com/MohamedOsama26/next-feature
homepage: https://github.com/MohamedOsama26/next-feature
issue_tracker: https://github.com/MohamedOsama26/next-feature/issues

environment:
  sdk: ^3.8.1

platforms:
  android:
  ios:
  linux:
  macos:
  windows:


# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.1
  prompts: ^2.0.0

# Add development dependencies here.
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

# Executables is for using this package as a command-line
# application with `dart run <package-name>` global command.
executables:
  next-feature: next_feature
