name: next_feature
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  interact: ^2.2.0
  path: ^1.9.1
  prompts: ^2.0.0

# Add development dependencies here.
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

# Executables is for using this package as a command-line
# application with `dart run <package-name>` global command.
executables:
  next_feature: next_feature
